Trix.config.lang.nl =
  bold: "Vet"
  bullets: "Bullets"
  byte:  "Byte"
  bytes: "Bytes"
  captionPlaceholder: "Type a caption here…"
  code: "Code"
  editCaption: "Edit caption"
  indent: "Increase Level"
  italic: "Cursief"
  link: "Link"
  numbers: "Genummerde lijst"
  outdent: "Decrease Level"
  quote: "Quote"
  redo: "Redo"
  remove: "Remove"
  strike: "Doorhalen"
  undo: "Undo"
  unlink: "Unlink"
  urlPlaceholder: "Type URL in…"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
  ins: "onderstrepen"
  grey: "grijs"
